# 데이터베이스 연결 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{로컬 DB 이름}?useSSL=false&serverTimezone=UTC
    username: {mysql username}
    password: {mysql password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
