# 데이터베이스 연결 설정
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret-key: ${JWT_SECRET_KEY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}